export enum AdvancePanchangApiActionTypes {
  FETCH_ADVANCE_PANCHANG_FETCH = 'FETCH_ADVANCE_PANCHANG_FETCH',
  FETCH_ADVANCE_PANCHANG_DATA = 'FETCH_ADVANCE_PANCHANG_DATA',
  FETCH_ADVANCE_PANCHANG_ERROR = 'FETCH_ADVANCE_PANCHANG_ERROR',
}

export enum MonthlyPanchangApiActionTypes {
  FETCH_MONTHLY_PANCHANG_FETCH = 'FETCH_MONTHLY_PANCHANG_FETCH',
  FETCH_MONTHLY_PANCHANG_FETCH_MULTI = 'FETCH_MONTHLY_PANCHANG_FETCH_MULTI',
  FETCH_MONTHLY_PANCHANG_DATA = 'FETCH_MONTHLY_PANCHANG_DATA',
  FETCH_MONTHLY_PANCHANG_ERROR = 'FETCH_MONTHLY_PANCHANG_ERROR',
}

export enum RealmActionTypes {
  INIT,
}
